# Generated by Django 5.2.17 on 2026-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_accounting",
            field=models.BooleanField(
                default=False,
                help_text="Darf die Zeiten aller Gruppen lesen und exportieren, aber nichts ändern.",
                verbose_name="Buchhaltung",
            ),
        ),
    ]
