# Generated by Django 5.2.17 on 2026-09-18 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Auch fuer andere Nutzer der Buchhaltung sichtbar.",
                        verbose_name="Geteilt",
                    ),
                ),
                ("columns", models.JSONField(default=list, verbose_name="Spalten")),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("entry", "Je Zeiteintrag"),
                            ("user_day", "Je Nutzer und Tag"),
                            ("user_month", "Je Nutzer und Monat"),
                            ("activity", "Je Taetigkeit"),
                        ],
                        default="entry",
                        max_length=16,
                        verbose_name="Verdichtung",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Filter"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geaendert am"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export-Vorlage",
                "verbose_name_plural": "Export-Vorlagen",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="unique_profile_name_per_owner"
                    )
                ],
            },
        ),
    ]
