# Generated by Django 5.2.17 on 2026-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportprofile",
            name="grouping",
            field=models.CharField(
                choices=[
                    ("entry", "Je Zeiteintrag"),
                    ("user_day", "Je Nutzer und Tag"),
                    ("user_month", "Je Nutzer und Monat"),
                    ("activity", "Je Tätigkeit"),
                ],
                default="entry",
                max_length=16,
                verbose_name="Verdichtung",
            ),
        ),
        migrations.AlterField(
            model_name="exportprofile",
            name="is_shared",
            field=models.BooleanField(
                default=False,
                help_text="Auch für andere Nutzer der Buchhaltung sichtbar.",
                verbose_name="Geteilt",
            ),
        ),
        migrations.AlterField(
            model_name="exportprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
        ),
    ]
