# Generated by Django 5.2.17 on 2026-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_alter_exportprofile_grouping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportprofile",
            name="grouping",
            field=models.CharField(
                choices=[
                    ("entry", "Je Zeiteintrag"),
                    ("user_day", "Je Nutzer und Tag"),
                    ("user_month", "Je Nutzer und Monat"),
                    ("user", "Je Nutzer"),
                    ("group", "Je Gruppe"),
                    ("activity", "Je Tätigkeit"),
                    ("cost_center", "Je Kostenstelle"),
                    ("cost_center_month", "Je Kostenstelle und Abrechnungszeitraum"),
                ],
                default="entry",
                max_length=24,
                verbose_name="Verdichtung",
            ),
        ),
    ]
