# Generated by Django 5.2.17 on 2026-09-21 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
        ("reporting", "0002_alter_exportprofile_grouping_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1 bis 28, damit es den Tag in jedem Monat gibt.",
                        verbose_name="Tag im Monat",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            (
                                "previous_period",
                                "Letzter abgeschlossener Abrechnungszeitraum",
                            ),
                            ("current_period", "Laufender Abrechnungszeitraum"),
                            ("last_twelve", "Die letzten zwölf Abrechnungszeiträume"),
                        ],
                        default="previous_period",
                        max_length=20,
                        verbose_name="Zeitraum",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("xlsx", "Excel (.xlsx)"), ("csv", "CSV")],
                        default="xlsx",
                        max_length=8,
                        verbose_name="Format",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="Empfänger"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Der Export läuft mit den Leserechten dieser Person.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Angelegt von",
                    ),
                ),
                (
                    "period_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bestimmt den Abrechnungszyklus. Ohne Auswahl gilt der Kalendermonat.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_schedules",
                        to="groups.group",
                        verbose_name="Zyklus der Gruppe",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reporting.exportprofile",
                        verbose_name="Vorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export-Zeitplan",
                "verbose_name_plural": "Export-Zeitpläne",
                "ordering": ["profile__name", "day_of_month"],
            },
        ),
        migrations.CreateModel(
            name="ExportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_on", models.DateField(verbose_name="Fällig am")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("sent", "Versandt"),
                            ("failed", "Fehlgeschlagen"),
                            ("blocked", "Dauerhaft fehlgeschlagen"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=1, verbose_name="Versuche"),
                ),
                ("started_at", models.DateTimeField(verbose_name="Begonnen am")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beendet am"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zeitraum von"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Zeitraum bis"
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(default=0, verbose_name="Zeilen"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Größe der Datei"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Meldung")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="reporting.exportschedule",
                        verbose_name="Zeitplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export-Lauf",
                "verbose_name_plural": "Export-Läufe",
                "ordering": ["-due_on", "-started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="exportschedule",
            constraint=models.UniqueConstraint(
                fields=("profile", "created_by", "day_of_month"),
                name="unique_schedule_per_profile_and_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 28)),
                name="schedule_day_between_1_and_28",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["schedule", "-due_on"], name="reporting_e_schedul_5a8727_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportrun",
            constraint=models.UniqueConstraint(
                fields=("schedule", "due_on"), name="unique_run_per_due_date"
            ),
        ),
    ]
