# Generated by Django 5.2.17 on 2026-09-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("open_entry", "Ausstempeln vergessen"),
                            ("pending_correction", "Antrag liegt offen"),
                            ("period_closing", "Zeitraum noch nicht abgeschlossen"),
                        ],
                        max_length=32,
                        verbose_name="Art",
                    ),
                ),
                (
                    "subject_key",
                    models.CharField(
                        help_text="Bezeichnet den Anlass, damit dieselbe Erinnerung nur einmal entsteht.",
                        max_length=100,
                        verbose_name="Anlass",
                    ),
                ),
                ("message", models.TextField(verbose_name="Hinweis")),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="Ziel"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Entstanden am"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erledigt am"
                    ),
                ),
                (
                    "emailed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Versandt am"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Empfänger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erinnerung",
                "verbose_name_plural": "Erinnerungen",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "resolved_at"],
                        name="reminders_r_recipie_702741_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "kind", "subject_key"),
                        name="unique_reminder_per_occasion",
                    )
                ],
            },
        ),
    ]
