# Generated by Django 5.2.17 on 2026-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open_entry", "Ausstempeln vergessen"),
                    ("pending_correction", "Antrag liegt offen"),
                    ("period_closing", "Zeitraum noch nicht abgeschlossen"),
                    ("correction_escalation", "Antrag bleibt liegen"),
                ],
                max_length=32,
                verbose_name="Art",
            ),
        ),
    ]
