# Generated by Django 5.2.17 on 2026-09-18 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edit", "Aenderung"),
                            ("create", "Nachtrag"),
                            ("delete", "Loeschung"),
                        ],
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "proposed_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gewuenschter Beginn"
                    ),
                ),
                (
                    "proposed_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gewuenschtes Ende"
                    ),
                ),
                (
                    "proposed_breaks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Gewuenschte Pausen"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Begruendung")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("withdrawn", "Zurueckgezogen"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entschieden am"
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(
                        blank=True, verbose_name="Begruendung der Entscheidung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gestellt am"),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_corrections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "proposed_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to="groups.activity",
                        verbose_name="Gewuenschte Taetigkeit",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Antragsteller",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_requests",
                        to="tracking.timeentry",
                        verbose_name="Zeiteintrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Korrekturantrag",
                "verbose_name_plural": "Korrekturantraege",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "group"], name="corrections_status_3e4a7a_idx"
                    )
                ],
            },
        ),
    ]
