# Generated by Django 5.2.17 on 2026-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionrequest",
            name="decision_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Solange leer, zaehlt die Entscheidung in der Navigation als neu.",
                null=True,
                verbose_name="Entscheidung gesehen am",
            ),
        ),
    ]
