# Generated by Django 5.2.17 on 2026-09-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0002_correctionrequest_decision_seen_at"),
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctionrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Korrekturantrag",
                "verbose_name_plural": "Korrekturanträge",
            },
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="decision_note",
            field=models.TextField(
                blank=True, verbose_name="Begründung der Entscheidung"
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="decision_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Solange leer, zählt die Entscheidung in der Navigation als neu.",
                null=True,
                verbose_name="Entscheidung gesehen am",
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("edit", "Änderung"),
                    ("create", "Nachtrag"),
                    ("delete", "Löschung"),
                ],
                max_length=10,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="proposed_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_requests",
                to="groups.activity",
                verbose_name="Gewünschte Tätigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="proposed_breaks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Gewünschte Pausen"
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="proposed_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Gewünschtes Ende"
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="proposed_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Gewünschter Beginn"
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="reason",
            field=models.TextField(verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                    ("withdrawn", "Zurückgezogen"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
