# Generated by Django 5.2.17 on 2026-09-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0003_alter_correctionrequest_options_and_more"),
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionrequest",
            name="applied_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_corrections",
                to="groups.activity",
                verbose_name="Übernommene Tätigkeit",
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="applied_breaks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Übernommene Pausen"
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="applied_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Übernommenes Ende"
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="applied_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Übernommener Beginn"
            ),
        ),
    ]
