# Generated by Django 5.2.17 on 2026-09-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corrections", "0004_correctionrequest_applied_activity_and_more"),
        ("groups", "0004_periodconfirmation"),
        ("tracking", "0004_entryimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correctionrequest",
            name="proposed_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur beim Gruppenwechsel: die Gruppe, in die der Eintrag soll.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_correction_requests",
                to="groups.group",
                verbose_name="Gewünschte Gruppe",
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="source_decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Zugestimmt am (bisherige Gruppe)"
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="source_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_decided_corrections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Zugestimmt von (bisherige Gruppe)",
            ),
        ),
        migrations.AddField(
            model_name="correctionrequest",
            name="source_note",
            field=models.TextField(
                blank=True, verbose_name="Bemerkung der bisherigen Gruppe"
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("edit", "Änderung"),
                    ("create", "Nachtrag"),
                    ("delete", "Löschung"),
                    ("move", "Gruppenwechsel"),
                ],
                max_length=10,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="correctionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("pending_target", "Wartet auf die neue Gruppe"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                    ("withdrawn", "Zurückgezogen"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionrequest",
            index=models.Index(
                fields=["status", "proposed_group"],
                name="corrections_status_01cc50_idx",
            ),
        ),
    ]
