# Generated by Django 5.2.17 on 2026-09-18 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Kurzname"
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kostenstelle"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt am"),
                ),
            ],
            options={
                "verbose_name": "Gruppe",
                "verbose_name_plural": "Gruppen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Mitglied"), ("admin", "Gruppen-Admin")],
                        default="member",
                        max_length=10,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Mitglied seit"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliedschaft",
                "verbose_name_plural": "Mitgliedschaften",
                "ordering": ["group__name", "user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="work_groups",
                through="groups.GroupMembership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mitglieder",
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deaktivierte Taetigkeiten sind nicht mehr waehlbar, alte Zeiteintraege bleiben erhalten.",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Reihenfolge"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taetigkeit",
                "verbose_name_plural": "Taetigkeiten",
                "ordering": ["group__name", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "name"), name="unique_activity_per_group"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_membership_per_group"
            ),
        ),
    ]
