# Generated by Django 5.2.17 on 2026-09-18 06:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="idp_identifier",
            field=models.CharField(
                blank=True,
                help_text="Name der Gruppe im Token des Identity-Providers. Leer bedeutet: es gilt der Kurzname.",
                max_length=200,
                verbose_name="Bezeichnung beim Identity-Provider",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="month_start_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1 bedeutet Kalendermonat. Bei 15 laeuft ein Zeitraum vom 15. bis zum 14. des Folgemonats. Hoechstens 28, damit es den Tag in jedem Monat gibt.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Beginn des Abrechnungszeitraums",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Im Tool zugeordnet"),
                    ("idp", "Aus dem Identity-Provider"),
                ],
                default="manual",
                help_text="Nur Mitgliedschaften aus dem Identity-Provider werden dort auch entzogen.",
                max_length=10,
                verbose_name="Herkunft",
            ),
        ),
        migrations.CreateModel(
            name="PeriodLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Beginn des Zeitraums")),
                ("period_end", models.DateField(verbose_name="Ende des Zeitraums")),
                (
                    "closed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Abgeschlossen am"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Bemerkung")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abgeschlossen von",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_locks",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abschluss",
                "verbose_name_plural": "Abschluesse",
                "ordering": ["-period_start", "group__name"],
                "indexes": [
                    models.Index(
                        fields=["group", "period_start", "period_end"],
                        name="groups_peri_group_i_7ae693_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "period_start"),
                        name="unique_period_lock_per_group",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="period_lock_end_after_start",
                    ),
                ],
            },
        ),
    ]
