# Generated by Django 5.2.17 on 2026-09-20 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_idp_identifier_group_month_start_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["group__name", "sort_order", "name"],
                "verbose_name": "Tätigkeit",
                "verbose_name_plural": "Tätigkeiten",
            },
        ),
        migrations.AlterModelOptions(
            name="periodlock",
            options={
                "ordering": ["-period_start", "group__name"],
                "verbose_name": "Abschluss",
                "verbose_name_plural": "Abschlüsse",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Deaktivierte Tätigkeiten sind nicht mehr wählbar, alte Zeiteinträge bleiben erhalten.",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="month_start_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1 bedeutet Kalendermonat. Bei 15 läuft ein Zeitraum vom 15. bis zum 14. des Folgemonats. Höchstens 28, damit es den Tag in jedem Monat gibt.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Beginn des Abrechnungszeitraums",
            ),
        ),
    ]
