# Generated by Django 5.2.17 on 2026-09-21 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Beginn des Zeitraums")),
                ("period_end", models.DateField(verbose_name="Ende des Zeitraums")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Bestätigt am"
                    ),
                ),
                (
                    "entry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Teil des bestätigten Stands: weicht die Anzahl später ab, ist die Bestätigung verfallen.",
                        verbose_name="Bestätigte Anzahl Zeiteinträge",
                    ),
                ),
                (
                    "last_change_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Teil des bestätigten Stands: wird danach noch eine Zeit geändert, ist die Bestätigung verfallen.",
                        null=True,
                        verbose_name="Jüngste Änderung im Zeitraum",
                    ),
                ),
                (
                    "total_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Die Summe, die beim Bestätigen auf dem Bildschirm stand.",
                        verbose_name="Bestätigte Summe in Minuten",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_confirmations",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_confirmations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestätigung des Zeitraums",
                "verbose_name_plural": "Bestätigungen des Zeitraums",
                "ordering": ["-period_start", "user__last_name", "user__first_name"],
                "indexes": [
                    models.Index(
                        fields=["group", "period_start"],
                        name="groups_peri_group_i_824b4b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group", "period_start"),
                        name="unique_period_confirmation_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="period_confirmation_end_after_start",
                    ),
                ],
            },
        ),
    ]
