# Generated by Django 5.2.17 on 2026-09-21 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_periodconfirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Begründung")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_source", "Wartet auf die bisherige Gruppe"),
                            ("pending_target", "Wartet auf die neue Gruppe"),
                            ("approved", "Genehmigt"),
                            ("rejected", "Abgelehnt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="pending_source",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source_decided_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Entschieden am (bisherige Gruppe)",
                    ),
                ),
                (
                    "source_note",
                    models.TextField(
                        blank=True, verbose_name="Bemerkung der bisherigen Gruppe"
                    ),
                ),
                (
                    "target_decided_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Entschieden am (neue Gruppe)",
                    ),
                ),
                (
                    "target_note",
                    models.TextField(
                        blank=True, verbose_name="Bemerkung der neuen Gruppe"
                    ),
                ),
                (
                    "decision_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Solange leer, zählt die Entscheidung in der Navigation als neu.",
                        null=True,
                        verbose_name="Entscheidung gesehen am",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gestellt am"),
                ),
                (
                    "from_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests_out",
                        to="groups.group",
                        verbose_name="Bisherige Gruppe",
                    ),
                ),
                (
                    "source_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_group_changes_out",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von (bisherige Gruppe)",
                    ),
                ),
                (
                    "target_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_group_changes_in",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entschieden von (neue Gruppe)",
                    ),
                ),
                (
                    "to_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests_in",
                        to="groups.group",
                        verbose_name="Neue Gruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Antragsteller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antrag auf Gruppenwechsel",
                "verbose_name_plural": "Anträge auf Gruppenwechsel",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "to_group"],
                        name="groups_grou_status_27042e_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_group", models.F("to_group")), _negated=True
                        ),
                        name="group_change_between_two_groups",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("pending_source", "pending_target"))
                        ),
                        fields=("user",),
                        name="one_open_group_change_per_user",
                    ),
                ],
            },
        ),
    ]
