# Generated by Django 5.2.17 on 2026-09-22 00:34

import apps.siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="Beschriftung")),
                (
                    "url",
                    apps.siteconfig.models.WebURLField(
                        max_length=300, verbose_name="Adresse"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Kleinere Zahlen stehen weiter vorne.",
                        verbose_name="Reihenfolge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verweis in der Fußzeile",
                "verbose_name_plural": "Verweise in der Fußzeile",
                "ordering": ["position", "label"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Zeiterfassung",
                        help_text="Steht in der Kopfzeile und im Titel des Browserfensters.",
                        max_length=60,
                        verbose_name="Name der Anwendung",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Erscheint in der Kopfzeile neben dem Namen und in der Fußzeile.",
                        max_length=120,
                        verbose_name="Firma",
                    ),
                ),
                (
                    "logo_data",
                    models.BinaryField(blank=True, default=b"", verbose_name="Logo"),
                ),
                (
                    "logo_content_type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=40,
                        verbose_name="Art des Logos",
                    ),
                ),
                (
                    "logo_filename",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=120,
                        verbose_name="Dateiname",
                    ),
                ),
                (
                    "logo_updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Logo geändert am",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Wird vorgelesen und angezeigt, solange das Bild fehlt. Leer: der Firmenname.",
                        max_length=120,
                        verbose_name="Beschreibung des Logos",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Zum Beispiel Anschrift oder Ansprechpartner. Zeilenumbrüche bleiben erhalten.",
                        verbose_name="Freitext in der Fußzeile",
                    ),
                ),
                (
                    "imprint_text",
                    models.TextField(
                        blank=True,
                        help_text="Steht als eigene Seite im Tool. Leer und ohne Adresse: kein Verweis.",
                        verbose_name="Impressum",
                    ),
                ),
                (
                    "imprint_url",
                    apps.siteconfig.models.WebURLField(
                        blank=True,
                        help_text="Verweis auf eine bestehende Seite. Gesetzt, gilt sie statt des Textes.",
                        max_length=300,
                        verbose_name="Impressum: Adresse",
                    ),
                ),
                (
                    "privacy_text",
                    models.TextField(
                        blank=True,
                        help_text="Steht als eigene Seite im Tool. Leer und ohne Adresse: kein Verweis.",
                        verbose_name="Datenschutz",
                    ),
                ),
                (
                    "privacy_url",
                    apps.siteconfig.models.WebURLField(
                        blank=True,
                        help_text="Verweis auf eine bestehende Seite. Gesetzt, gilt sie statt des Textes.",
                        max_length=300,
                        verbose_name="Datenschutz: Adresse",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
            ],
            options={
                "verbose_name": "Darstellung",
                "verbose_name_plural": "Darstellung",
            },
        ),
    ]
