# Generated by Django 5.2.17 on 2026-09-26 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Nur der Teil nach dem @, zum Beispiel firma.de.",
                        max_length=253,
                        unique=True,
                        validators=[
                            django.core.validators.DomainNameValidator(
                                accept_idna=False
                            )
                        ],
                        verbose_name="Domäne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail-Domäne",
                "verbose_name_plural": "Mail-Domänen",
                "ordering": ["domain"],
            },
        ),
    ]
