# Generated by Django 5.2.17 on 2026-09-18 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("clock_in", "Eingestempelt"),
                            ("clock_out", "Ausgestempelt"),
                            ("break_start", "Pause begonnen"),
                            ("break_end", "Pause beendet"),
                            ("auto_close", "Automatisch beendet"),
                            ("entry_updated", "Zeiteintrag geaendert"),
                            ("entry_deleted", "Zeiteintrag geloescht"),
                            ("correction_requested", "Korrektur beantragt"),
                            ("correction_approved", "Korrektur genehmigt"),
                            ("correction_rejected", "Korrektur abgelehnt"),
                            ("correction_withdrawn", "Korrektur zurueckgezogen"),
                            ("export", "Export erstellt"),
                        ],
                        max_length=32,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Objektart"
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Objekt-Id"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Aenderungen"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Bemerkung")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handelnde Person",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries_about_me",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Betroffene Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokolleintrag",
                "verbose_name_plural": "Protokoll",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__2d648a_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_6e540c_idx"
                    ),
                ],
            },
        ),
    ]
