# Generated by Django 5.2.17 on 2026-09-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("clock_in", "Eingestempelt"),
                    ("clock_out", "Ausgestempelt"),
                    ("break_start", "Pause begonnen"),
                    ("break_end", "Pause beendet"),
                    ("auto_close", "Automatisch beendet"),
                    ("entry_updated", "Zeiteintrag geaendert"),
                    ("entry_deleted", "Zeiteintrag geloescht"),
                    ("correction_requested", "Korrektur beantragt"),
                    ("correction_approved", "Korrektur genehmigt"),
                    ("correction_rejected", "Korrektur abgelehnt"),
                    ("correction_withdrawn", "Korrektur zurueckgezogen"),
                    ("export", "Export erstellt"),
                    ("period_closed", "Zeitraum abgeschlossen"),
                    ("period_reopened", "Zeitraum wieder geoeffnet"),
                    ("user_anonymized", "Konto anonymisiert"),
                    ("membership_synced", "Mitgliedschaften abgeglichen"),
                    ("group_created", "Gruppe angelegt"),
                    ("notification_failed", "Benachrichtigung fehlgeschlagen"),
                ],
                max_length=32,
                verbose_name="Aktion",
            ),
        ),
    ]
