# Generated by Django 5.2.17 on 2026-09-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("clock_in", "Eingestempelt"),
                    ("clock_out", "Ausgestempelt"),
                    ("break_start", "Pause begonnen"),
                    ("break_end", "Pause beendet"),
                    ("auto_close", "Automatisch beendet"),
                    ("entry_updated", "Zeiteintrag geändert"),
                    ("entry_deleted", "Zeiteintrag gelöscht"),
                    ("correction_requested", "Korrektur beantragt"),
                    ("correction_approved", "Korrektur genehmigt"),
                    ("correction_rejected", "Korrektur abgelehnt"),
                    ("correction_withdrawn", "Korrektur zurückgezogen"),
                    ("export", "Export erstellt"),
                    ("period_closed", "Zeitraum abgeschlossen"),
                    ("period_reopened", "Zeitraum wieder geöffnet"),
                    ("user_anonymized", "Konto anonymisiert"),
                    ("user_updated", "Stammdaten geändert"),
                    ("membership_synced", "Mitgliedschaften abgeglichen"),
                    ("group_created", "Gruppe angelegt"),
                    ("notification_failed", "Benachrichtigung fehlgeschlagen"),
                ],
                max_length=32,
                verbose_name="Aktion",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Änderungen"),
        ),
    ]
