# Generated by Django 5.2.17 on 2026-09-18 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Beginn")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("clock", "Gestempelt"),
                            ("correction", "Korrigiert"),
                            ("import", "Importiert"),
                        ],
                        default="clock",
                        max_length=12,
                        verbose_name="Erfassungsart",
                    ),
                ),
                (
                    "is_incomplete",
                    models.BooleanField(
                        default=False,
                        help_text="Automatisch beendet, weil das Ausstempeln vergessen wurde.",
                        verbose_name="Unvollstaendig",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geaendert am"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="groups.activity",
                        verbose_name="Taetigkeit",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="groups.group",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeiteintrag",
                "verbose_name_plural": "Zeiteintraege",
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="BreakEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Beginn")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "is_automatic",
                    models.BooleanField(default=False, verbose_name="Automatisch"),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="tracking.timeentry",
                        verbose_name="Zeiteintrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pause",
                "verbose_name_plural": "Pausen",
                "ordering": ["start"],
            },
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["user", "-start"], name="tracking_ti_user_id_358ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["group", "-start"], name="tracking_ti_group_i_aed3a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end__isnull", True)),
                fields=("user",),
                name="unique_open_time_entry_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end__isnull", True),
                    ("end__gt", models.F("start")),
                    _connector="OR",
                ),
                name="time_entry_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="breakentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end__isnull", True)),
                fields=("time_entry",),
                name="unique_open_break_per_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="breakentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end__isnull", True),
                    ("end__gt", models.F("start")),
                    _connector="OR",
                ),
                name="break_end_after_start",
            ),
        ),
    ]
