# Generated by Django 5.2.17 on 2026-09-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_activity_options_alter_periodlock_options_and_more"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeentry",
            options={
                "ordering": ["-start"],
                "verbose_name": "Zeiteintrag",
                "verbose_name_plural": "Zeiteinträge",
            },
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_entries",
                to="groups.activity",
                verbose_name="Tätigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="is_incomplete",
            field=models.BooleanField(
                default=False,
                help_text="Automatisch beendet, weil das Ausstempeln vergessen wurde.",
                verbose_name="Unvollständig",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
        ),
    ]
