# Generated by Django 5.2.17 on 2026-09-21 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_timeentry_no_overlap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dateiname"
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(default=b"", verbose_name="Dateiinhalt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("prepared", "Geprüft"), ("applied", "Übernommen")],
                        default="prepared",
                        max_length=10,
                        verbose_name="Stand",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Zusammenfassung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Übernommen am"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeitimport",
                "verbose_name_plural": "Zeitimporte",
                "ordering": ["-created_at"],
            },
        ),
    ]
